name : Run the API Automation Test 
on: workflow_dispatch
jobs:
  Demo:
   runs-on: ubuntu-latest
   steps:
    - name: Get Code 
      uses: actions/checkout@v4
    - name: Install Java in Runner
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '11'
    - name: Test Java Installation
      run: | 
           java HelloWorldApp.java  
           java --version    
    # - name: Run Test
    #   run: mvn clean test 
    