name : Run the API Automation Test | Maven CI/CD
on: push
jobs:
  Demo:
   runs-on: ubuntu-latest
   steps:
    - name: Get Code 
      uses: actions/checkout@v4
    - name: Cache  local Maven repository
      id:   cache
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-m2
    - name: Install Java in Runner
      if : steps.cache.outputs.cache-hit != 'true'
      uses: actions/setup-java@v4
      with:
        distribution: 'jetbrains'
        java-version: '11'
    - name: Test Java Installation
      run: | 
           java --version
    - name: Change Dir 
      run: |
           cd /home/runner/work/APIAutomationWithGitHubAction/APIAutomationWithGitHubAction            
    - name: Run Test
      run: mvn clean test
    - name: Upload Artifact 
      uses: actions/upload-artifact@v4
      with:
        name: Test_Result 
        path: |
             test-output
             target
    - name: Download Test Result
      uses: actions/download-artifact@v4   
      with:
        name: Test_Result

    